# Site settings
title: Alberto Galarza
description: Jekyll Theme Minimal Resume
# baseurl: "https://github.com/albertogalarza"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alberto Galarza
user_description: Natural leader and entrepreneur skilled in managing people, finance, marketing, financial analysis, data analytics, R, python, SQL, and Tableau. Fully bilingual in Spanish & English. I have a B.S. degree, double majoring in Finance and Management from New Mexico State University. Google Data Analytics Certified. Currently enrolled in the Google Advanced Data Analytics Course. Actively upgrading my skillsets to join a company and grow as a professional. <br><br>In my current role, I am a Financial Analyst for GPS Insight in Scottsdale, Arizona. I work directly under the VP of FP&A & the CFO, where I analyze financial data & statements using advanced MS Excel & powerBI skills to evaulate performance metrics, forecast trends and support strategic decision making. I also own my own event company, Lotus Entertainment, focusing on Live Events in Texas & New Mexico.<br><br>Outside of professionalism, I spend most of my weekends working out, reading, socializing, trying out a new restaurant, taking a random class on a random topic, boxing, & watching sci-fi movies or DragonBall Z.<br><br>Just a simple guy, with big dreams. 
user_title: Data Analytics | Data Visualization | Statistics | Finance | Management
email: albertgalarza.ag@gmail.com
linkedin_username: albertgalarza
github_username:  albertgalarza
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
